import { Theme } from "../theme.slint";
import { Store } from "../store.slint";
import { Logic } from "../logic.slint";
import { Dialog } from "./dialog.slint";
import { LineInput } from "line-input.slint";

export component RenameDialog inherits Dialog {
    title: Logic.tr("Rename");
    is-prevent-event-forward: true;

    in-out property text <=> line-input.text;

    callback rename(text: string);

    confirmed => {
        rename(root.text);
    }

    canceled => {
        self.escape();
    }

    Timer {
        private property <bool> is-running: true;

        interval: 200ms;
        running: is-running;
        triggered() => {
            is-running = false;
            line-input.focus();
        }
    }

    VerticalLayout {
        padding: Theme.padding * 2;
        padding-top: Theme.padding * 4;

        line-input := LineInput {
            accepted => {
                rename(root.text);
            }
        }
    }
}
